#! /usr/bin/bash

#! /usr/bin/bash
echo "Deleting S3 stack via AWS CloudFormation..."

STACK_NAME="s3-stack"

if aws cloudformation delete-stack --stack-name $STACK_NAME --region ap-northeast-1 --no-cli-auto-prompt; then
    echo "Stack $STACK_NAME deleted successfully"
fi
